[profile.default]
solc = "0.8.29"
src = "src"
out = "out"
libs = ["lib"]
via-ir = true
optimizer = true
optimizer_runs = 833
evm_version = "cancun"
fs_permissions = [{ access = "read-write", path = "./deployments/"}]
block_gas_limit = 10000000000

[profile.lite.optimizer_details.yulDetails]
optimizerSteps = ''

[fmt]
bracket_spacing = false
int_types = "long"
line_length = 120
multiline_func_header = "params_first"
quote_style = "double"
tab_width = 4
wrap_comments = true
